### ISSUE TITLE
Missing dependency on `qtpy`

### ISSUE THREAD

**Issue by LaurentRDC** [conda-forge/qdarkstyle-feedstock#12]
Installing `qdarkstyle` is not sufficient; `qtpy` is a dependency (see [here](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/6aef1de7e97227899c478a5634d136d80991123e/setup.py#L16)) but it is not listed in the `recipe.yaml` file.

**Comment by ccordoba12** [comment]
You're totally right! I don't know how we missed this!

Please open a pull request to add `qtpy` and `helpdev` to the list of runtime dependencies.
